spring.application.name=springboot-web
server.port=8090
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
spring.web.locale-resolver=fixed
spring.web.locale=es_ES

